name: 'Slither Analysis'

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop

jobs:
  slither-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-f625d0fa7c51e65b4bf1e8f7931cd1c6e2e285e9

      - name: Install slither-analyzer
        run: python -m pip install slither-analyzer==0.10.2

      - name: Run Slither
        id: slither
        run: |
          slither packages/contracts-bedrock \
          --sarif results.sarif \
          --triage-database packages/contracts-bedrock/slither.db.json \
          --config-file packages/contracts-bedrock/slither.config.json
          echo "sarif=results.sarif" >> $GITHUB_OUTPUT

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
